### ISSUE TITLE
Loss of numeric precision for large JSON numbers

### ISSUE THREAD

**Issue by travishaagen** [nhooyr/websocket#184]
I discovered that the current JSON unmarshalling code was converting all numeric JSON values to `float64`, and that it was losing numeric precision for large numbers.

I was able to fix the issue locally by using the following code:

```
func read(ctx context.Context, c *websocket.Conn, v interface{}) error {
	typ, r, err := c.Reader(ctx)
	if err != nil {
		return err
	}

	if typ != websocket.MessageText {
		c.Close(websocket.StatusUnsupportedData, "can only accept text messages")
		return fmt.Errorf("unexpected frame type for json (expected %v): %v", websocket.MessageText, typ)
	}

	d := json.NewDecoder(r)
	// IMPORTANT: UseNumber to preserve numeric precision
	d.UseNumber()
	if err := d.Decode(&v); err != nil {
		c.Close(websocket.StatusInvalidFramePayloadData, "failed to decode JSON")
		return fmt.Errorf("failed to decode json: %w", err)
	}

	return nil
}
```

See https://golang.org/pkg/encoding/json/#Decoder.UseNumber

It would be nice if this library could better handle this situation.

**Comment by nhooyr** [comment]
This is certainly unfortunate but I don't think there are any good adjustments we can make in wsjson to alleviate this. I considered passing a config into Read but given that is an edge case, I don't think it's a good idea.

I would instead marshal numbers as strings as if you do read such JSON in javascript, it will be truncated since all numbers are represented as floats there.

**Comment by nerg4l** [comment]
You should be able to use `big.Float`.
