### ISSUE TITLE
Conn.Close should prevent all writes after writing the close frame

### ISSUE THREAD

**Issue by zhangyoufu** [nhooyr/websocket#213]
From [RFC6455 §1.4](https://tools.ietf.org/html/rfc6455#section-1.4):
> After sending a control frame indicating the connection should be closed, a peer does not send any further data

Current implementation does not obey this rule.

**Comment by nhooyr** [comment]
How does it not obey this rule?

**Comment by nhooyr** [comment]
Once Close is called, nothing else can ever be written.

**Comment by zhangyoufu** [comment]
> Once Close is called, nothing else can ever be written.

It takes a long time until `defer conn.close(nil)` happen. If you look at on-wire packets, there can be many data frames being sent after the close frame.

**Comment by nhooyr** [comment]
Fair enough, it doesn't explicitly prevent you from writing any additional data but once the peer receives a close frame, it stops reading from the connection so writing any additional garbage data isn't an issue. The RFC states that so that the peer knows not to read anything after a close.

Making all writes after a close frame fail should be really easy anyway so lets take care of this.
