### ISSUE TITLE
Abstract away http.Client

### ISSUE THREAD

**Issue by andersfylling** [nhooyr/websocket#249]
I'm writing a new client library for discord websocketing, and I won't to have proper testing from the start and replacing the http.Client with an interface allows me to mock responses based on the http request:
```go
type HttpClienter interface {
	Do(req *http.Request) (*http.Response, error)
}
```

Is this something you would consider for this library?

**Comment by nhooyr** [comment]
You can already do this by abstracting `http.Transport` in `*http.Client`.

**Comment by nhooyr** [comment]
Sorry I meant implementing `http.Transport`.

**Comment by ipfans** [comment]
@nhooyr A little different requirement about this. For example, we have a custom httpclient that includes features such as our built-in security authentication certificate, retries, and circuit breaker. However, since this library uses *http.Client, this prevents us using these features. It is also very complicated to wrap the corresponding functionality. Currently, there is no use to more internals, interfaces is a very good solution.

**Comment by nhooyr** [comment]
Those features should be in an `http.Transport` implementation, not an abstraction around `*http.Client`.
