### ISSUE TITLE
wasm: Dial context timeout does not work sometimes

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/websocket#272]
Was reported to me by @TheDiscordian on reddit.

The problem is this line:

https://github.com/nhooyr/websocket/blob/c9f314abd11b749d43bb61fd214171f8bb4e4173/ws_js.go#L280

The close call will wait for the connection to open thus voiding the context timeout.

@TheDiscordian reported that putting the close into a new goroutine worked.
I think this is because we unbind the OnOpen listener when returning from dial and thus c.Close errors out instead of waiting for the connection to succeed.

**Comment by TheDiscordian** [comment]
Moving this line into a goroutine has worked well for me. It's not clear to me why, but the context does work correctly like this. I should note though, that anyone trying to open websockets faster than the browser would like (due to technical limitations or security policies) may run into unexpected behaviours like ALL future websockets failing without a real error. A page refresh will fix this (can be triggered in script).

Otherwise, I've had no noticeable troubles running the library this way. I was using contexts for an address scanner, and the address scanner works faster, and more stable with this change.

**Comment by nhooyr** [comment]
@TheDiscordian What browser are you using? I wrote a test and confirmed the context deadline does work. The close call above does not wait for the connection to open first and instead closes it quickly as expected. I'm testing on chromium.

See 65dfbdd

**Comment by TheDiscordian** [comment]
> @TheDiscordian What browser are you using? I wrote a test and confirmed the context deadline does work. The close call above does not wait for the connection to open first and instead closes it quickly as expected. I'm testing on chromium.
> 
> See [65dfbdd](https://github.com/nhooyr/websocket/commit/65dfbdd4c1106a9529bbf374aa92ea97a4456c2a)

It's possible it could have been a bug in my browser. I'll run the test when I get a chance (repairing HDD right now). I don't know what version I was on when I reported the bug, but I was using Opera and Firefox. I was testing using 10 second timeouts, on specifically local IP addresses like 192.168.0.2, I could not reproduce the issue using WAN IPs.

**Comment by nhooyr** [comment]
Bizarre. Can you test in chromium and see if you can still reproduce?

**Comment by nhooyr** [comment]
Going to close as I was unable to reproduce.
