### ISSUE TITLE
Need to check if all data sent

### ISSUE THREAD

**Issue by nskforward** [nhooyr/websocket#305]
In **write.go** file function **Write** does not return the number of actually sent bytes.
So currently I cannot do the second assertion in code below:

```
n, err := conn.Write(ctx, websocket.MessageBinary, data)
if err != nil {
...
}
if len(data) != n {
// send remaining bytes in the next Write call or throw an error
}
```

**Comment by Agnewee** [comment]
in my opinion, you no need to care about `the number of actually sent bytes`
function `conn.Write` write all the number of your send bytes done if the `err` is nil, alse means `n == len(data)`

**Comment by nhooyr** [comment]
Hello @nskforward!

So there are generally no write errors on which it makes sense to retry in Go.

First, you might get an error because you cannot write to the socket anymore. The peer may have explicitly disconnected, the peer may not be responding or some operating system limit may have been exceeded. It doesn't make sense to retry here as the connection is effectively unsable in some way and your application should release the associated resources.

Second, a deadline may have been triggered. Here you could retry but it doesn't make much sense. If a deadline was triggered, then the peer is too slow to receive your messages. Rather than retrying, why not just make your write deadline longer? If you're using a small deadline to do some sort of polling in your write goroutine then you'd be misusing Go as the purpose of goroutines and IO built into the runtime is to avoid you having to do that kind of stuff manually.

It might make sense to write an error in a multistream protocol where you could use a different stream to let the peer know they're being disconnected for being too slow but WebSockets is unfortunately not such a protocol.

But regardless, with this library you currently don't have the choice to retry as the API exposed to us by `*http.Client` for upgrading connections does not allow interrupting in progress writes without closing the entire connection. So *any* error returned from a write means you cannot write again as either the connection is broken or a write deadline was triggered and so the connection was closed to free any goroutine currently stuck in a Write.

See https://github.com/nhooyr/websocket/issues/242

**Comment by nhooyr** [comment]
Apologies for the delayed response!
