### ISSUE TITLE
Sending incorrect json to wsjson.Read closes connection

### ISSUE THREAD

**Issue by Anupam-Ashish-Minz** [nhooyr/websocket#399]
I don't know where this is intended or not but it seem that sending incorrect json data to wsjson.Read closes the websocket connection even though an error object is returned.

Incorrect json data like
```json
{
  "message": "hello world"
} something
```

Here a part of my code 
```go
var v interface{}
for {
    err = wsjson.Read(ctx, ws, &v)
    if err != nil {
        log.Println(err)
        continue
    }
    log.Println(v)
}
```

I was trying to continue using the connect in spite of error however this causes the connection to close and an infinite loop to run continuously printing the error.

**Comment by nhooyr** [comment]
Why do you want to try and reuse the connection if you read corrupted JSON? There's no way for you to do anything useful with the connection if the data you're reading is corrupt.

**Comment by nhooyr** [comment]
Feel free to comment when you can and I'll reopen.

**Comment by aadithyen** [comment]
Well I agree that most of the time misformatted JSON won't come through. Might be better to close the connection and retry. But rather than wson.Read closing it, I think it would be better if it just returns an error and leaves it to the caller to handle it however they want, such as if they want to return an error, or log the scenario before closing.

**Comment by nhooyr** [comment]
I don't understand the purpose of that. What does giving the caller that flexibility do? They'll just have to close it themselves in the same way we do here. Just more code for them.

**Comment by aadithyen** [comment]
Maybe returning a bad request response before or instead of closing the connection.

**Comment by nhooyr** [comment]
The code closes with the proper close status and error message so that shouldn't be necessary in most cases.

See https://github.com/nhooyr/websocket/blob/master/wsjson/wsjson.go#L39

In the cases where it is, where you do want to send your own protocol level error message first, then I think it's ok to write your own helpers instead of using `wsjson` as `wsjson` is for the common case. See also #418

I've opened #450 to document this at least.

**Comment by achsvg** [comment]
> Why do you want to try and reuse the connection if you read corrupted JSON? There's no way for you to do anything useful with the connection if the data you're reading is corrupt.

In our case we'd like to send an error message back to the user, prompting him to retry with a well formatted json without having to re-open a websocket connection.
